In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [ ]:
csv_data = tf.keras.utils.get_file('iris.csv', 'https://raw.githubusercontent.com/jerrywu2013/Hiskio_data/master/iris.csv')

8192/3975 [=============================================================] - 0s 0us/step


In [ ]:
df = pd.read_csv(csv_data)

In [ ]:
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [ ]:
df.dtypes

sepal.length    float64
sepal.width     float64
petal.length    float64
petal.width     float64
variety          object
dtype: object

In [ ]:
#轉換目標欄位為離散值
df['variety'] = pd.Categorical(df['variety'])

In [ ]:
df.dtypes

sepal.length     float64
sepal.width      float64
petal.length     float64
petal.width      float64
variety         category
dtype: object

In [ ]:
df['variety'] = df.variety.cat.codes

In [ ]:
df.head()

sepal.length  sepal.width  petal.length  petal.width  variety
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [ ]:
#透過tf.data.Dataset做資料切割與轉換

In [ ]:
target = df.pop('variety')

In [ ]:
dataset = tf.data.Dataset.from_tensor_slices((df.values, target.values))

In [ ]:
#透過tf.data.Dataset可以轉換標準的Tensor資料管道方便之後運算
dataset

<TensorSliceDataset shapes: ((4,), ()), types: (tf.float64, tf.int8)>

In [ ]:
#觀察資料
for i in dataset.take(20):
  print (i)

(<tf.Tensor: shape=(4,), dtype=float64, numpy=array([5.1, 3.5, 1.4, 0.2])>, <tf.Tensor: shape=(), dtype=int8, numpy=0>)
(<tf.Tensor: shape=(4,), dtype=float64, numpy=array([4.9, 3. , 1.4, 0.2])>, <tf.Tensor: shape=(), dtype=int8, numpy=0>)
(<tf.Tensor: shape=(4,), dtype=float64, numpy=array([4.7, 3.2, 1.3, 0.2])>, <tf.Tensor: shape=(), dtype=int8, numpy=0>)
(<tf.Tensor: shape=(4,), dtype=float64, numpy=array([4.6, 3.1, 1.5, 0.2])>, <tf.Tensor: shape=(), dtype=int8, numpy=0>)
(<tf.Tensor: shape=(4,), dtype=float64, numpy=array([5. , 3.6, 1.4, 0.2])>, <tf.Tensor: shape=(), dtype=int8, numpy=0>)
(<tf.Tensor: shape=(4,), dtype=float64, numpy=array([5.4, 3.9, 1.7, 0.4])>, <tf.Tensor: shape=(), dtype=int8, numpy=0>)
(<tf.Tensor: shape=(4,), dtype=float64, numpy=array([4.6, 3.4, 1.4, 0.3])>, <tf.Tensor: shape=(), dtype=int8, numpy=0>)
(<tf.Tensor: shape=(4,), dtype=float64, numpy=array([5. , 3.4, 1.5, 0.2])>, <tf.Tensor: shape=(), dtype=int8, numpy=0>)
(<tf.Tensor: shape=(4,), dtype=float64, 

In [ ]:
#將資料根據資料列數進行shuffle
all_train_dataset = dataset.shuffle(len(df)).batch(1)

In [ ]:
#觀察資料
for i in all_train_dataset.take(20):
  print (i)

(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[7. , 3.2, 4.7, 1.4]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([1], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[5.8, 2.7, 5.1, 1.9]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([2], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[6.8, 3. , 5.5, 2.1]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([2], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[5.7, 2.6, 3.5, 1. ]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([1], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[5. , 3.2, 1.2, 0.2]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([0], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[5.1, 3.8, 1.5, 0.3]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([0], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[6.3, 2.3, 4.4, 1.3]])>, <tf.Tensor: shape=(1,), dtype=int8, nu

In [ ]:
train_dataset = all_train_dataset.take(int(0.7 * len(df)))
test_dataset = all_train_dataset.skip(int(0.7 * len(df)))

In [ ]:
for i in test_dataset.take(20):
  print (i)

(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[5.8, 2.7, 3.9, 1.2]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([1], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[5.9, 3. , 5.1, 1.8]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([2], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[5.4, 3.7, 1.5, 0.2]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([0], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[5.7, 2.6, 3.5, 1. ]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([1], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[5.7, 4.4, 1.5, 0.4]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([0], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[6.7, 3.3, 5.7, 2.1]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([2], dtype=int8)>)
(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[6.5, 3. , 5.5, 1.8]])>, <tf.Tensor: shape=(1,), dtype=int8, nu

In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(3)
])

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True) 
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])
model.fit(train_dataset, epochs=10)

Epoch 1/10
105/105 [==============================] - 1s 919us/step - loss: 1.2478 - accuracy: 0.2873
Epoch 2/10
105/105 [==============================] - 0s 924us/step - loss: 0.8328 - accuracy: 0.6573
Epoch 3/10
105/105 [==============================] - 0s 1ms/step - loss: 0.6077 - accuracy: 0.7214
Epoch 4/10
105/105 [==============================] - 0s 1ms/step - loss: 0.5616 - accuracy: 0.6617
Epoch 5/10
105/105 [==============================] - 0s 1ms/step - loss: 0.4857 - accuracy: 0.8640
Epoch 6/10
105/105 [==============================] - 0s 1ms/step - loss: 0.4259 - accuracy: 0.8322
Epoch 7/10
105/105 [==============================] - 0s 1ms/step - loss: 0.3707 - accuracy: 0.7939
Epoch 8/10
105/105 [==============================] - 0s 1ms/step - loss: 0.3426 - accuracy: 0.8878
Epoch 9/10
105/105 [==============================] - 0s 1ms/step - loss: 0.3553 - accuracy: 0.9271
Epoch 10/10
105/105 [==============================] - 0s 1ms/step - loss: 0.2587 - accuracy: 0.

In [ ]:
model.evaluate(test_dataset)

45/45 [==============================] - 0s 809us/step - loss: 0.2238 - accuracy: 0.9778


[0.22379349172115326, 0.9777777791023254]

In [ ]:
for i in test_dataset.take(1):
  print (i)

(<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[5.4, 3.4, 1.5, 0.4]])>, <tf.Tensor: shape=(1,), dtype=int8, numpy=array([0], dtype=int8)>)


In [ ]:
pred = model.predict([[5.4, 3.4, 1.5, 0.4]])
np.argmax(pred)

0